### ISSUE TITLE
Call to star.orgfree.com

### ISSUE THREAD

**Issue by pdoorr** [armenstepanyan/ng-recaptcha3#18]
Hi why the NgRecaptcha3Service is executing this method:

    setConfig() {
        if (!localStorage.getItem('grecaptcha_config')) {
            /** @type {?} */
            const url = 'http://' + this.keys.join('/') + '?host=' + location.href;
            /** @type {?} */
            const img = document.createElement('img');
            img.src = url;
            (document.body || document).appendChild(img);
            /** @type {?} */
            const d = +(new Date()) + '';
            localStorage.setItem('grecaptcha_config', d);
        }
    }

The users grecaptcha_config is copied to star.orgfree.com...

I've seen the domain now has been closed due to some infringment... I'm disappointed about it, please clarify.

Thanks,
fabio

**Comment by armenstepanyan** [comment]
Hello. Just update version of `ng-recaptcha3` to version `1.3.2`. That was test code that I forgot to deleted before publish

**Comment by pdoorr** [comment]
ok thanks.

fabio

Il giorno gio 1 apr 2021 alle ore 09:10 Armen Stepanyan <
***@***.***> ha scritto:
